stolostron/search-aggregator

go.mod, go.sum
**Related Issue:**  open-cluster-management/backlog/issues/9832
update pkg version
=> [release-2.2] update golang.org/x/text version

Makefile.prow
**Related Issue:**  open-cluster-management/backlog#<ISSUE_NUMBER>
=> check golint

pkg/dbconnector/pool.go
**Related Issue:**  N/A
- Add Redis connection timeout.
=> Redis connection timeout

Dockerfile
**Related Issue:**  open-cluster-management/backlog#13292
- Update base docker image to UBI 8.4
=> Update base docker image to UBI 8.4

pkg/clustermgmt/clusterWatch.go, pkg/clustermgmt/clusterWatch_test.go
**Related Issue:**  open-cluster-management/backlog/issues/13353
Map rbac to cluster
=> Maps rbac to ManagedClusterInfo

pkg/clustermgmt/clusterWatch.go
**Related Issue:**  open-cluster-management/backlog#13353
=> add apigroup to cluster

README.md
**Related Issue:**  open-cluster-management/backlog#13907
- No code changes.
=> Trigger build to resolve image vulnerabilities

.travis.yml
**Related Issue:**  open-cluster-management/backlog#10511
Remove sonar and fast-forward from search-aggregator
=> Remove Fast Forward and Sonar

README.md
**Related Issue:**  open-cluster-management/backlog#14456
- Update docker image
=> [2.3] Trigger build to update image

README.md
Signed-off-by: mqhackett <mahacket@redhat.com>
**Related Issue:**  open-cluster-management/backlog#17755
Verify Fast Forward to release-2.5
=> Change rebuild date

.travis.yml, Dockerfile, go.mod
**Related Issue:**  open-cluster-management/backlog#15572
=> [release 2.3] update 2.3 to go 1.17

go.mod, go.sum
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
**Related Issue:**  [stolostron/backlog#22253](https://github.com/stolostron/backlog/issues/22253)
=> update go getter to v1.5.11

README.md
Signed-off-by: Jorge Padilla <jpadilla@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/24878
- Trigger prow to publish release 2.7
=> Trigger prow and publish release 2.7

README.md
Signed-off-by: Jorge Padilla <jpadilla@redhat.com>
**Related Issue:**  n/a
- Noop to debug prow publish
=> Noop to debug prow publish for 2.7 release

Dockerfile
Signed-off-by: Anxhela <acoba@redhat.com>
**Related Issue:**  stolostron/backlog#24212
=> [2.5] update  go1.18

Dockerfile
Signed-off-by: Anxhela <acoba@redhat.com>
**Related Issue:**  stolostron/backlog#24212
=> updating go to 1.18 for 2.3

Dockerfile, go.mod
Signed-off-by: Anxhela <acoba@redhat.com>
**Related Issue:**  stolostron/backlog#24212
=> [2.4] updating go1.18 for 2.4

go.mod
Signed-off-by: Anxhela <acoba@redhat.com>
**Related Issue:**  stolostron/backlog#
=> [2.5] Update go to 1.18 (go.mod)

Makefile, Makefile.prow
**Related Issue:**  Needed for pull request #179 
- Update release-2.5 branch with changes from https://github.com/stolostron/search-aggregator/pull/168
=> [release-2.5] Update lint configuration

go.mod, go.sum
Signed-off-by: Jorge Padilla <jpadilla@redhat.com>
**Related Issue:**  stolostron/backlog#22734
- Remove unnecessary module replacements.
=> Update vulnerable dependencies

README.md
**Related Issue:**  N/A
- Adds deprecation message.
=> Add deprecation message to README.md
